version: "3.7"

services: 
  backend:
    image: quizz-back
    build:
      context: backend
    restart: always
    environment: 
      DEBUG: 1
    ports: 
      - 8010:8000
    volumes:
      - ./backend/src:/app/backend

  frontend-vite:
    image: quiz-front
    build:
      context: frontend-vite
    restart: always
    environment: 
      - CHOKIDAR_USEPOLLING=true
    ports: 
     - 3000:3000
    volumes:
     - ./frontend-vite:/app/
